### ISSUE TITLE
Responsive Image

### ISSUE THREAD

**Issue by winstonma** [ibrahimcesar/react-lite-youtube-embed#1]
Currently the package loads the hqdefault image. 

I am using your package and bootstrap to display the youtube on a website. Therefore it would be great if the choice of image could be based on the width of the frame (e.g. load mqdefault on mobile and maxresdefault on desktop).

EDIT: I just saw it is configurable. Just wonder if it is possible that it is automatic.

**Comment by ibrahimcesar** [comment]
Great idea! I'll work on this for a next release.

Thanks!

**Comment by winstonma** [comment]
I would like to add some comment here.

I used to use the [lazyYT](https://github.com/Daugilas/lazyYT) and it would load the image accordingly. The logic is inside [lazyYT.js](https://github.com/Daugilas/lazyYT/blob/master/lazyYT.js).

**Comment by ibrahimcesar** [comment]
Thanks @winstonma , I'll take a look!
