### ISSUE TITLE
Title not showing up

### ISSUE THREAD

**Issue by icy-meteor** [ibrahimcesar/react-lite-youtube-embed#11]
The title of the video doesn't show up even after passing it as a prop.
![image](https://user-images.githubusercontent.com/22114682/108842321-1ab34a80-75ff-11eb-823c-34d0c803fc45.png)

Rendered:
![image](https://user-images.githubusercontent.com/22114682/108842279-0a9b6b00-75ff-11eb-88ea-5842a2a9cef1.png)

**Comment by ibrahimcesar** [comment]
Passing the prop as title is not to show in your UI, but in the alt description, to increase accessibility
