### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by kimkim480** [ibrahimcesar/react-lite-youtube-embed#12]
I tried to use in a project with NextJs and typescript but got the following message "Cannot find module 'react-lite-youtube-embed' or its corresponding type declarations.ts(2307)"

Not sure if I am doing something wrong but I would appreciate if I could use your component  :D

**Comment by ibrahimcesar** [comment]
Please, get the latest version 1.0.49 – I tested now on NextJS 10.0.1 – and it was with a bug for the whole lib import. Thanks!

**Comment by kimkim480** [comment]
It works now. thank you!
