### ISSUE TITLE
API control of 1 or more videos

### ISSUE THREAD

**Issue by yumenochikara** [ibrahimcesar/react-lite-youtube-embed#18]
**Is your feature request related to a problem? Please describe.**
I have a project which has multiple embedded videos, and I would like to control each one of them with the YouTube API, which seems impossible.

**Describe the solution you'd like**
I would love some additional parameters to the "LiteYoutubeEmbed" tag that would enable the API commands.

**Comment by ibrahimcesar** [comment]
@yumenochikara 

Sorry for the late response.

Could you please share more about your use case? I don't use it with the YT API. We have a prop `onIframeAdded` that you can attach a function at each frame once loaded. Did you tried use that?
