### ISSUE TITLE
Announce property is not optional

### ISSUE THREAD

**Issue by j9141997** [ibrahimcesar/react-lite-youtube-embed#24]
**Describe the bug**
TypeScript detected an error 'announce is declared here.
An additional implementation of the "announce" property was added in version 2.0.6, but README.md indicates that it is an optional property.

**Screenshots**
<img width="860" alt="screenshot 2021-09-01 20 57 19" src="https://user-images.githubusercontent.com/50947613/131667330-5f6532fe-25c7-4fac-8caf-e09ff1ce6015.png">

**Comment by ibrahimcesar** [comment]
My mistake! I'll fix it right away. Thanks @j9141997 !

**Comment by ibrahimcesar** [comment]
@j9141997 just release the patch. Thanks!

https://github.com/ibrahimcesar/react-lite-youtube-embed/releases/tag/v2.0.7

**Comment by schoenwaldnils** [comment]
Still (or again?) not optional 🤔
https://github.com/ibrahimcesar/react-lite-youtube-embed/blob/main/src/lib/index.tsx#L11
