### ISSUE TITLE
Have to press pay button twice on safari

### ISSUE THREAD

**Issue by jonrrivera** [ibrahimcesar/react-lite-youtube-embed#35]
**Describe the bug**
I have to press the play button trice to play the video on safari

**To Reproduce**
open: https://www.thisiscoin.com/watch
on safari
and click on the play button. you will see that it props you to play again

**Expected behavior**
should play only clicking once

**Screenshots**

**Desktop (please complete the following information):**
Safari Version 14.0.3 (16610.4.3.1.4)

**Comment by avinfors** [comment]
Hi, guys! I have same problem on Android mobile browsers (Chrome, Firefox).

**Comment by anlanzino** [comment]
> Thanks @jonrrivera , I'll take a look this week.

Were you ever able to get around to this? I'm having the same issue on Safari.

**Comment by ibrahimcesar** [comment]
Bug fixed in version `v2.1.1` published to npm today

**Comment by ibrahimcesar** [comment]
Safari 11 now [disables/blocks autoplay features](https://www.howtogeek.com/326532/safari-now-disables-auto-playing-videos.-heres-how-to-allow-them-for-certain-sites/). You have to [manually go to the safari settings and Allow All Auto-Play](https://support.apple.com/en-mn/guide/safari/stop-autoplay-videos-ibrw29c6ecf8/mac).

**Comment by spencerwhyte** [comment]
On desktop Safari this works fine with cookie={true} and fails otherwise......

**Comment by spencerwhyte** [comment]
Likely to do with my auto-play settings for https://www.youtube-nocookie.com vs https://www.youtube.com like you said.
