### ISSUE TITLE
Iframe/component should display decent view once video completes 

### ISSUE THREAD

**Issue by adgang** [ibrahimcesar/react-lite-youtube-embed#37]
**Is your feature request related to a problem? Please describe.**
When a video playing is complete, the iframe shows irrelevant video suggestions which are out of place for an embedding website.

**Describe the solution you'd like**
Embed APIs has events support. Based on the player state, we can give a better behavior when the video ends, say, showing a thumbnail or taking the video back to time=0.

**Describe alternatives you've considered**
Using playlist mitigates the issue, but it is not optimal for all cases. The problematic views still come up at the end of playlist.

Screenshot upon video completion:
![sin-embed](https://user-images.githubusercontent.com/12166343/141533754-e28b0292-4e48-4387-9027-2030fc9f5869.png)

**Additional context**

**Comment by ibrahimcesar** [comment]
Hello @adgang , I also don't like the recommended by YouTube.

Currently we don't have any integration with YouTube API to handle this use-case. I try to maintain this lib as small as possible. 

Maybe an extension? We had another requests and use-cases that uses YouTube API.

**Comment by ibrahimcesar** [comment]
Marked as closed since is content problem, with YouTube, and we can deal within this component.
