### ISSUE TITLE
Doesn't work with Next.js

### ISSUE THREAD

**Issue by mirshko** [ibrahimcesar/react-lite-youtube-embed#4]
Is it possible to export the styles separately? 

<img width="594" alt="Screen Shot 2020-04-26 at 13 27 17" src="https://user-images.githubusercontent.com/8116716/80306127-a7b02c00-87c1-11ea-98e3-1e44b652ac0f.png">

**Comment by elbotho** [comment]
Had the same problem, if you need a quickfix for that I made a version that does not include the css, so you can use it with nextjs and need to include the styles your own way.

works for me if I install from `elbotho/react-lite-youtube-embed.git#fix-for-nextjs`

**Comment by elbotho** [comment]
More on the issue here:
https://github.com/zeit/next.js/blob/master/errors/css-npm.md

**Comment by elbotho** [comment]
@ibrahimcesar is there a reason you are not using webpack?

**Comment by ibrahimcesar** [comment]
@elbotho No, besides I didn't think at the time. In fact this was my first open sourced project! I must thank you all the feedback and sorry for the late response!

**Comment by elbotho** [comment]
@ibrahimcesar no worries, thanks for your work on this!
Not sure about merging my "solution" it's more of workaround because it forces you to import css manually.

**Comment by yulev5** [comment]
Hello
So is there a solution for working with this library with Nextjs?

**Comment by ibrahimcesar** [comment]
@yulev5 Not at the moment, but I'll work on that soon. Subscribe to this issue and I'll let you know.

**Comment by yulev5** [comment]
> @yulev5 Not at the moment, but I'll work on that soon. Subscribe to this issue and I'll let you know.

Thank you

**Comment by ibrahimcesar** [comment]
@yulev5 The new version should work fine with NextJS but it will need some integration in order to the CSS work, I updated the README, but if you fid any problem in order to make work, please create an issue!

**Comment by murillo94** [comment]
for those who work with nextjs, you can also now use the https://www.npmjs.com/package/@next/third-parties


```
import { YouTubeEmbed } from '@next/third-parties/google'

export default function Page() {
  return <YouTubeEmbed videoid="ogfYd705cRs" height={400} />
}
```
